metainfo:
    gender: 'male'
    data_dir : /home/flynn/arc/vr/v2a/vid2avatar/data/hi4d_pair21
    subject: all_frames.pkl
    start_frame: 11
    end_frame: 111
    body_params_loader: zju
    chromo: True
    data_provider: hi4d

train:
    type: "VideoZju"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 0
    num_sample : 2048
    cameras: [0, 1, 2, 3, 4, 5, 6, 7]
    cache: True

valid:
    - type: "VideoZjuVal"
      image_id: 0
      batch_size: 1
      drop_last: False
      shuffle: False
      worker: 0
      num_sample : -1
      pixel_per_batch: 2048
      cameras: [7,]
      cache: False

test:
    - type: "VideoZjuTest"
      image_id: 0
      batch_size: 1
      drop_last: False
      shuffle: False
      worker: 0
      num_sample : -1
      pixel_per_batch: 2048
      cameras: [0]
      cache: False
