metainfo:
    gender: 'neutral'
    data_dir : /home/flynn/vr_docker_shared_common/datasets/zjumocap
    subject: CoreView_392
    start_frame: 0
    end_frame: 299
    body_params_loader: zju
    chromo: True

train:
    type: "VideoZju"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 0
    num_sample : 2048
    cameras: [0, 6, 12, 18]

valid:
    - type: "VideoZjuVal"
      image_id: 0
      batch_size: 1
      drop_last: False
      shuffle: False
      worker: 0
      num_sample : -1
      pixel_per_batch: 2048
      cameras: [3,]

test:
    - type: "VideoZju"
      image_id: 0
      batch_size: 1
      drop_last: False
      shuffle: False
      worker: 0
      num_sample : -1
      pixel_per_batch: 2048
      cameras: [2,]
