hydra:
    run:
        dir: "outputs/${exp}/${run}"

defaults:
  - model: model_w_bg_decrease_lr_earlier
  - dataset: ffcache_hi4d_test
  - trainer: base
  - _self_

seed: 42
project_name: "model_w_bg"
exp: 'decrease_lr_earlier_chromo_lots_or_rays_hi4d'
run: ${dataset.metainfo.subject}