hydra:
    run:
        dir: "../outputs/${exp}/${run}"

defaults:
  - model: model_w_bg_decrease_lr_earlier
  - dataset: video_zju
  - trainer: base
  - _self_

seed: 42
project_name: "model_w_bg"
exp: 'decrease_lr_earlier'
run: ${dataset.metainfo.subject}